# Generated by Django 6.0.5 on 2026-06-08 10:36

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.CharField(default=chat.models.generate_chat_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
