# Generated by Django 6.0.5 on 2026-06-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='invite_mode',
            new_name='invite_code',
        ),
    ]
